INSERT INTO UTILISATEUR(NOM, MOT_PASSE) VALUES('ricardo', '123456');
INSERT INTO UTILISATEUR(NOM, MOT_PASSE) VALUES('thuana', '112233');

INSERT INTO PRODUIT(ID,CODE,NOM,PRIX,DESCRIPTION,FABRICANT) VALUES(1,'2344XH','Z5', 1190.99, 'Celulaire Z5', 'Sony');
INSERT INTO PRODUIT(ID,CODE,NOM,PRIX,DESCRIPTION,FABRICANT) VALUES(2,'7485RT','K10', 790.99, 'Celulaire K10', 'LG');
INSERT INTO PRODUIT(ID,CODE,NOM,PRIX,DESCRIPTION,FABRICANT) VALUES(3,'8743KW','MOTO G', 870.99, 'Celulaire MOTO G', 'Motorola');
